;;; helm-cscope-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-cscope.el

(autoload 'helm-cscope-find-this-symbol "helm-cscope" "\
Locate a symbol in source code.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-this-symbol-no-prompt "helm-cscope" "\
Locate a symbol in source code [no user prompting]." t)
(autoload 'helm-cscope-find-global-definition "helm-cscope" "\
Find a symbol's global definition.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-global-definition-no-prompt "helm-cscope" "\
Find a symbol's global definition [no user prompting]." t)
(autoload 'helm-cscope-find-called-function "helm-cscope" "\
Display functions called by a function.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-called-function-no-prompt "helm-cscope" "\
Display functions called by a function [no user prompting]." t)
(autoload 'helm-cscope-find-calling-this-function "helm-cscope" "\
Display functions calling a function.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-calling-this-function-no-prompt "helm-cscope" "\
Display functions calling a function [no user prompting]." t)
(autoload 'helm-cscope-find-this-text-string "helm-cscope" "\
Locate where a text string occurs.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-this-text-string-no-prompt "helm-cscope" "\
Locate where a text string occurs [no user prompting]." t)
(autoload 'helm-cscope-find-egrep-pattern "helm-cscope" "\
Run egrep over the cscope database.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-this-file "helm-cscope" "\
Locate a file.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-this-file-no-prompt "helm-cscope" "\
Locate a file [no user prompting]." t)
(autoload 'helm-cscope-find-files-including-file "helm-cscope" "\
Locate all files #including a file.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-assignments-to-this-symbol "helm-cscope" "\
Locate assignments to a symbol in the source code.

(fn SYMBOL)" t)
(autoload 'helm-cscope-find-assignments-to-this-symbol-no-prompt "helm-cscope" "\
Locate assignments to a symbol in the source code[no user prompting]." t)
(autoload 'helm-cscope-mode "helm-cscope" "\
Toggle Helm-Cscope mode on or off.

This is a minor mode.  If called interactively, toggle the
`Helm-Cscope mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `helm-cscope-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "helm-cscope" '("helm-cscope-"))

;;; End of scraped data

(provide 'helm-cscope-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-cscope-autoloads.el ends here
