;;; enclose-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from enclose.el

(autoload 'enclose-mode "enclose" "\
Enclose cursor within punctuation pairs.

This is a minor mode.  If called interactively, toggle the
`enclose mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `enclose-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'turn-on-enclose-mode "enclose" "\
Turn on `enclose-mode'." t)
(autoload 'turn-off-enclose-mode "enclose" "\
Turn off `enclose-mode'." t)
(put 'enclose-global-mode 'globalized-minor-mode t)
(defvar enclose-global-mode nil "\
Non-nil if Enclose-Global mode is enabled.
See the `enclose-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `enclose-global-mode'.")
(custom-autoload 'enclose-global-mode "enclose" nil)
(autoload 'enclose-global-mode "enclose" "\
Toggle Enclose mode in all buffers.
With prefix ARG, enable Enclose-Global mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Enclose mode is enabled in all buffers where `turn-on-enclose-mode'
would do it.

See `enclose-mode' for more information on Enclose mode.

(fn &optional ARG)" t)
(register-definition-prefixes "enclose" '("enclose"))

;;; End of scraped data

(provide 'enclose-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; enclose-autoloads.el ends here
