;;; recently-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from recently.el

(defvar recently-mode nil "\
Non-nil if Recently mode is enabled.
See the `recently-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `recently-mode'.")
(custom-autoload 'recently-mode "recently" nil)
(autoload 'recently-mode "recently" "\
Track recently opened files.

When enabled it records recently opened file paths, and
view list and visit again via `recently-show' command.

This is a global minor mode.  If called interactively, toggle the
`Recently mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='recently-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'recently-show "recently" "\
Show buffet that lists recently opened files.
BUFFER-NAME, if given, should be a string for buffer to create.

(fn &optional BUFFER-NAME)" t)
(register-definition-prefixes "recently" '("recently-"))

;;; End of scraped data

(provide 'recently-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; recently-autoloads.el ends here
