;;; term-run-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from term-run.el

(autoload 'term-run "term-run" "\
Run PROGRAM in BUFFER-OR-NAME with ARGS in terminal buffer.

If BUFFER-OR-NAME is given, use this buffer.  In this case, old process in the
buffer will be destroyed.  Otherwise, new buffer will be generated automatically
from PROGRAM.

This function returns the buffer where the process starts running.

(fn PROGRAM &optional BUFFER-OR-NAME &rest ARGS)")
(autoload 'term-run-shell-command "term-run" "\
Run COMMAND in terminal buffer.

If NEW-BUFFER-P is given or called with prefix argument, generate new terminal
buffer for running COMMAND.  Otherwise, use the same buffer.  In this case, old
process in the buffer will be destroyed after asking to user.

This function returns the buffer where the process starts running.

(fn COMMAND &optional NEW-BUFFER-P)" t)
(register-definition-prefixes "term-run" '("term-run-shell-command-history"))

;;; End of scraped data

(provide 'term-run-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; term-run-autoloads.el ends here
