;;; helm-fish-completion-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-fish-completion.el

(autoload 'helm-fish-completion "helm-fish-completion" "\
Helm interface for fish completion.
This is mostly useful for `M-x shell'.
For Eshell, see `helm-fish-completion-make-eshell-source'." t)
(autoload 'helm-fish-completion-make-eshell-source "helm-fish-completion" "\
Make and return Helm sources for Eshell.
This is a good candidate for `helm-esh-pcomplete-build-source-fn'.
For `M-x shell', use `helm-fish-completion' instead.")
(register-definition-prefixes "helm-fish-completion" '("helm-fish-completion-"))

;;; End of scraped data

(provide 'helm-fish-completion-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-fish-completion-autoloads.el ends here
