;;; mutt-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mutt-mode.el

(autoload 'mutt-mode "mutt-mode" "\
Major mode for editing mutt configuration files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.muttrc\\'" . mutt-mode))
(add-to-list 'auto-mode-alist '("\\<muttrc\\'>" . mutt-mode))
(register-definition-prefixes "mutt-mode" '("mutt-"))

;;; End of scraped data

(provide 'mutt-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mutt-mode-autoloads.el ends here
