;;; project-treemacs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from project-treemacs.el

(autoload 'project-treemacs-try "project-treemacs" "\
Treemacs backend for use in `project-find-functions'.

Tests whether DIR is a member of a visible `treemacs' project.

(fn DIR)")
(defvar project-treemacs-mode nil "\
Non-nil if Project-Treemacs mode is enabled.
See the `project-treemacs-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `project-treemacs-mode'.")
(custom-autoload 'project-treemacs-mode "project-treemacs" nil)
(autoload 'project-treemacs-mode "project-treemacs" "\
Toggles treemacs backend for project.el.

When enabled, by default, treemacs backend is prefered over other backends, but
see `project-treemacs-prefer-backend' user option.

This is a global minor mode.  If called interactively, toggle the
`Project-Treemacs mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='project-treemacs-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "project-treemacs" '("project-treemacs-"))

;;; End of scraped data

(provide 'project-treemacs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; project-treemacs-autoloads.el ends here
