;;; helm-codesearch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-codesearch.el

(autoload 'helm-codesearch-find-pattern "helm-codesearch" "\
Find pattern." t)
(autoload 'helm-codesearch-find-file "helm-codesearch" "\
Find file." t)
(autoload 'helm-codesearch-create-csearchindex "helm-codesearch" "\
Create index file at DIR.

(fn DIR)" t)
(register-definition-prefixes "helm-codesearch" '("helm-codesearch-"))

;;; End of scraped data

(provide 'helm-codesearch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-codesearch-autoloads.el ends here
