;;; color-theme-approximate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from color-theme-approximate.el

(autoload 'color-theme-approximate-on "color-theme-approximate" nil t)
(autoload 'color-theme-approximate-off "color-theme-approximate" nil t)
(register-definition-prefixes "color-theme-approximate" '("ca-"))

;;; End of scraped data

(provide 'color-theme-approximate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; color-theme-approximate-autoloads.el ends here
