;;; helm-google-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-google.el

(autoload 'helm-google "helm-google" "\
Web search interface for Emacs.

(fn &optional ENGINE SEARCH-TERM)" t)
(autoload 'helm-google-searx "helm-google" "\
Explicitly use Searx for the web search.

(fn &optional SEARCH-TERM)" t)
(autoload 'helm-google-google "helm-google" "\
Explicitly use Google for the web search.

(fn &optional SEARCH-TERM)" t)
(register-definition-prefixes "helm-google" '("helm-google-"))

;;; End of scraped data

(provide 'helm-google-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-google-autoloads.el ends here
