;;; find-file-in-repository-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from find-file-in-repository.el

(autoload 'find-file-in-repository "find-file-in-repository" "\
find-file-in-repository will autocomplete all files in the
   current git, mercurial or other type of repository, using
   ido-find-file when available. When the current file is not
   located inside of any repository, falls back on a regular
   find-file operation." t)
(defalias 'ffir 'find-file-in-repository)
(put 'ffir-repository-types 'safe-local-variable 'listp)
(put 'ffir-avoid-HOME-repository 'safe-local-variable 'booleanp)
(register-definition-prefixes "find-file-in-repository" '("ffi"))

;;; End of scraped data

(provide 'find-file-in-repository-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; find-file-in-repository-autoloads.el ends here
