;;; ivy-omni-org-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ivy-omni-org.el

(autoload 'ivy-omni-org "ivy-omni-org" "\
Ivy interface to buffers, files, and bookmarks in Org.

When TYPES is a list of symbols, this function limits the content
types to it.

(fn &key TYPES)" t)
(autoload 'ivy-omni-org-bookmarks "ivy-omni-org" "\
Display a list of bookmarks." t)
(register-definition-prefixes "ivy-omni-org" '("ivy-omni-org-"))

;;; End of scraped data

(provide 'ivy-omni-org-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ivy-omni-org-autoloads.el ends here
